name: be_social
description: A social network designed for lonely people who want to step out of their zone.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.0
  pedantic: ^1.9.2

  cloud_firestore: ^0.16.0
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  redux: ^4.0.0+3
  redux_epics: ^0.14.0
  flutter_redux: ^0.7.0

  built_value: ^7.1.0
  built_collection: ^4.3.2
  freezed_annotation: ^0.12.0
  meta: ^1.2.4
  http: ^0.12.2

dependency_overrides:
  rxdart: ^0.25.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  built_value_generator: ^7.1.0
  build_runner: any
  freezed: any
  analyzer: any

flutter:
  uses-material-design: true